### ISSUE TITLE
Is this the latest/definitive version of CNearTree?

### ISSUE THREAD

**Issue by Tyler799** [yayahjb/neartree#1]
I see that there is also the original SourceForge page here: https://sourceforge.net/projects/neartree/

Though it isn't marked as deprecated, and the original page: http://neartree.sourceforge.net/ is still on sourceforge as well.

May end up contributing to this for some cleanup, but unsure. I see a large sum of completely unused variables, shadowed declarations, set-but-unused variables, large sums of duplicated code and a very...inconsistent style.

Some heavy warning flags to find and perform clean-up and something like ```clang-format``` might help a lot.

But I won't do that until I'm sure this is the main site and is being maintained enough to accept a PR.

**Comment by Tyler799** [comment]
As a sidenote, it seems this may be based off a C++ version. Where can that be found? Is its performance better/worse/the same?

**Comment by yayahjb** [comment]
Yes, this the version that is under current development, but first it needs some reorganization to split it into NearTree and DataGen, and then some cleanup is done
to remove some of the variations that have been carried for a while as you note, but are no longer needed.   Your question about C++ will be answered if you drop into the NearTree folder, read the README and run the tests.  The you will see both the C++ (Tnear.h)  and C version  are there.  You should view the C++ version as the primary algorithmic development environment.  Since you don't seem to have a code-specific issue at this time, I am going to close this issue.  When you have a substantive issue, let us know.
